# https://www.de-online.ru/gram-tabelle/tablica_Deutsch-online.pdf  
Scheme.create rule: 'e-a-o',    assoc: 'пЕдАгОг',   sample: 'брать — nehmen — nahm — genommen'
Scheme.create rule: 'e-o-o',    assoc: 'бЕльмОндО', sample: 'поднимать — heben — hob — gehoben'
Scheme.create rule: 'ei-i-i',   assoc: 'дАЙкИрИ',   sample: 'резать — schneiden — schnitt — geschnitten'
Scheme.create rule: 'ei-ie-ie', assoc: 'дАЙкИрИ',   sample: 'писать — sreiben — srieb — gesrieben'
Scheme.create rule: 'ei-ie-ei'
Scheme.create rule: 'i-a-o',    assoc: 'пИфАгОр',   sample: 'побеждать — gewinnen — gewann — gewonnen'
Scheme.create rule: 'i-a-e',    assoc: 'дИАбЕт',    sample: 'просить — bitten — bat — gebeten'
Scheme.create rule: 'i-a-u',    assoc: 'сИрАкУзы',  sample: 'находить — finden — fand — gefunden'
Scheme.create rule: 'ie-o-o',   assoc: 'кИмОнО',    sample: 'летать — fliegen — flog — geflogen'
Scheme.create rule: 'o-ie-u'
Scheme.create rule: 'u-ie-u',                       sample: 'кричать, звать — rufen — rief — gerufen'
Scheme.create rule: 'ö-o-o',    assoc: 'бЕльмОндО'
Scheme.create rule: 'ü-o-o',    assoc: 'бЕльмОндО', sample: 'лгать - lügen - log - gelog'
Scheme.create rule: 'e-i-a',                        sample: 'отправляться — gehen — ging — gegangen'
Scheme.create rule: 'nicht anwendbar'
Scheme.create rule: 'nicht definiert'
